<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ensie\UserBundle\Event\EventListeners;

use FOS\UserBundle\Event\FormEvent;
use FOS\UserBundle\Event\GetResponseUserEvent;
use FOS\UserBundle\EventListener\ResettingListener as BaseListener;
use FOS\UserBundle\FOSUserEvents;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class ResettingListener extends BaseListener
{
    private $router;
    private $tokenTtl;

    public function __construct(UrlGeneratorInterface $router, $tokenTtl)
    {
        parent::__construct($router, $tokenTtl); // TODO: Change the autogenerated stub
        $this->router = $router;
        $this->tokenTtl = $tokenTtl;
    }


    public function onResettingResetSuccess(FormEvent $event)
    {
        parent::onResettingResetSuccess($event); // TODO: Change the autogenerated stub
        $response = new RedirectResponse($this->router->generate('fos_user_reset_success'));
        $event->setResponse($response);
    }


}
