<?php
/**
 * Created by PhpStorm.
 * User: Badjak
 * Date: 22-7-14
 * Time: 21:02
 */

namespace Ensie\UserBundle\Controller;

use FOS\UserBundle\Controller\SecurityController as BaseController;
use Ensie\LanguageBundle\Traits\GetCurrentLanguageTrait;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\SecurityContextInterface;

class SecurityController extends BaseController
{
    use GetCurrentLanguageTrait;

    public function checkAction()
    {
        parent::checkAction(); // TODO: Change the autogenerated stub
    }


    public function loginAction(Request $request)
    {
        return parent::loginAction($request);
        //return $this->loginRedirectAction();
    }

    public function loginRedirectAction(){
        return new RedirectResponse($this->container->get('router')->generate('home').'?login');
    }

}