<?php
/**
 * Created by PhpStorm.
 * User: Badjak
 * Date: 31-8-14
 * Time: 10:48
 */

namespace Ensie\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class EditUserLinkedInType extends EditUserType{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->remove('username');
    }


    public function getName()
    {
        return 'ensie_user_linked_in_profile';
    }

} 