services:
    sonata.admin.language_language:
        class: Ensie\LanguageBundle\Admin\LanguageAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Languages"
        arguments:
            - ~
            - Ensie\LanguageBundle\Entity\Language
            - ~
        calls:
            - [ setTranslationDomain, [EnsieLanguageBundle]]