<?php

namespace Ensie\BadgesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EarnedBadgesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EarnedBadgesRepository extends EntityRepository
{
}
