<?php
/**
 * Created by PhpStorm.
 * User: Badjak
 * Date: 11-9-14
 * Time: 19:50
 */

namespace Ensie\EnsieBundle\Validator\Constraint;


use Symfony\Component\Validator\Constraint;

class UniqueDefinition extends Constraint{

    public $message = 'Only one word in the same language is allowed';

    public function validatedBy()
    {
        return 'ensie.validator_one_definition_per_user_language'; // TODO: Change the autogenerated stub
    }


} 