<?php
/**
 * Created by PhpStorm.
 * User: Badjak
 * Date: 11-9-14
 * Time: 19:50
 */

namespace Ensie\EnsieBundle\Validator\Constraint;

use Symfony\Component\Validator\Constraint;

class UniqueEnsie extends Constraint{

    public $message = 'Only one ensie is allowed';

    public function validatedBy()
    {
        return 'ensie.validator_one_ensie_per_user_language'; // TODO: Change the autogenerated stub
    }
} 