_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_install:
    resource: "@EnsieEnsieBundle/Controller/InstallController.php"
    type:     annotation


#test urls
error_500:
    defaults:  { _controller: EnsieEnsieBundle:Test:error500 }
    path:   /test/error/500

error_403:
    defaults:  { _controller: EnsieEnsieBundle:Test:error403 }
    path:   /test/error/403

email_stats:
    defaults:  { _controller: EnsieEnsieBundle:Test:emailStats }
    path:   /test/emailstats

mandrill_test:
    defaults:  { _controller: EnsieEnsieBundle:Test:mandrillTest }
    path:   /test/mandrill

mandrill_mailer_test:
    defaults:  { _controller: EnsieEnsieBundle:Test:mandrillMailer }
    path:   /test/mandrillmailer

_main:
    resource: routing.yml
