<?php
/**
 * Created by PhpStorm.
 * User: Badjak
 * Date: 9-11-14
 * Time: 11:00
 */

namespace Ensie\MandrillMailerBundle\Mandrill\Template\DataGetter;

class ContactWriterDataGetter extends UserDataGetter{

    public function validate()
    {
        parent::validate(); // TODO: Change the autogenerated stub
        if(empty($this->extraData) or !isset($this->extraData['DESCRIPTION'])){
            throw new \Exception('DESCRIPTION is not set.');
        }
        if(empty($this->extraData) or !isset($this->extraData['URL'])){
            throw new \Exception('URL is not set.');
        }
        if(empty($this->extraData) or !isset($this->extraData['EMAIL'])){
            throw new \Exception('EMAIL is not set.');
        }
    }

} 