<?php

namespace Ensie\EnsieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ensie\EnsieBundle\Event\Events\SpamDefinitionEvent;
use Ensie\EnsieBundle\Event\Events\SpamEvents;
use Ensie\UserBundle\Entity\EnsieUser;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

/**
 * SpamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpamRepository extends EntityRepository
{

    /** @var  EventDispatcherInterface */
    private $eventDispatcher;

    public function setEventDispatcher(EventDispatcherInterface $eventDispatcher){
        $this->eventDispatcher = $eventDispatcher;
    }

    /**
     * @param Definition $definition
     * @param EnsieUser $user
     * @param $description
     * @return Spam
     */
    public function create(Definition $definition, EnsieUser $user, $description){
        $spam = new Spam();
        $spam->setDefinition($definition);
        $spam->setIpAddress($_SERVER['REMOTE_ADDR']);
        $spam->setDescription($description);
        $spam->setUser($user);
        $this->getEntityManager()->persist($spam);
        //Trigger event
        $this->eventDispatcher->dispatch(SpamEvents::ENSIE_DEFINITION_SPAM_REPORTED, new SpamDefinitionEvent($definition, $user, $spam));
        return $spam;
    }

    public function getByUserAndDefinition(Definition $definition, EnsieUser $user){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('spam');
        $qb->from('Ensie\EnsieBundle\Entity\Spam','spam');
        $qb->where('spam.definition = :definition');
        $qb->andWhere('spam.user = :user');
        $qb->setParameter('definition', $definition);
        $qb->setParameter('user', $user);
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @param Definition $definition
     * @return double
     */
    public function countSpams(Definition $definition)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('avg(spam.spam)');
        $qb->from('Ensie\EnsieBundle\Entity\Spam','spam');
        $qb->where('spam.definition = :definition');
        $qb->setParameter('definition', $definition);

        return $qb->getQuery()->getSingleScalarResult();
    }

}
