<?php

namespace Ensie\EnsieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository
{
    public function getSubcategoryBySlug($subcategorySlug)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('subcategory');
        $qb->from('Ensie\EnsieBundle\Entity\Subcategory', 'subcategory');
        $qb->andWhere('subcategory.slug = :slug');
        $qb->setParameter('slug', $subcategorySlug);
        return $qb->getQuery()->getResult();
    }

    public function getSubcategoriesByCategory(Category $category)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('subcategory, category');
        $qb->from('Ensie\EnsieBundle\Entity\Subcategory', 'subcategory');
        $qb->setParameter('category', $category);
        return $qb->getQuery()->getResult();
    }
}
