<?php

namespace Ensie\EnsieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ensie\UserBundle\Entity\EnsieUser;

/**
 * ViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends EntityRepository
{

    /**
     * @param Definition $definition
     * @param EnsieUser $user
     * @return View
     */
    public function create(Definition $definition, EnsieUser $user = null){
        $view = new View();
        $view->setDefinition($definition);
        $view->setIpAddress($_SERVER['REMOTE_ADDR']);
        if($user){
            $view->setUser($user);
        }
        $this->getEntityManager()->persist($view);
        return $view;
    }

    /**
     * @param Definition $definition
     * @return integer
     */
    public function countViews(Definition $definition)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(view.id)');
        $qb->from('Ensie\EnsieBundle\Entity\View','view');
        $qb->where('view.definition = :definition');
        $qb->setParameter('definition', $definition);

        return $qb->getQuery()->getSingleScalarResult();
    }

}
